#ifndef _INPUT_
#define _INPUT_

#include "common.h"

OLDTECH_BEGIN_HEADER

typedef enum {
    KEY_Esc = 1,
    KEY_1 = 2,
    KEY_2 = 3,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_Minus,
    KEY_Equals,
    KEY_Backspace,
    KEY_Tab,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LeftBracket,
    KEY_RightBracket,
    KEY_Enter,
    KEY_LeftControl,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_Semicolon,
    KEY_Apostrophe,
    KEY_Grave,
    KEY_LeftShift,
    KEY_BackSlash,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_Comma,
    KEY_Period,
    KEY_Slash,
    KEY_RightShift,
    KEY_Multiply,
    KEY_LeftAlt,
    KEY_Space,
    KEY_Capital,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NumLock,
    KEY_Scroll,
    KEY_NumPad7,
    KEY_NumPad8,
    KEY_NumPad9,
    KEY_SUBTRACT,
    KEY_NUMPAD4,
    KEY_NUMPAD5,
    KEY_NUMPAD6,
    KEY_ADD,
    KEY_NUMPAD1,
    KEY_NUMPAD2,
    KEY_NUMPAD3,
    KEY_NUMPAD0,
    KEY_Decimal,
    KEY_OEM_102,
    KEY_F11,
    KEY_F12,
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_KANA,
    KEY_ABNT_C1,
    KEY_CONVERT,
    KEY_NOCONVERT,
    KEY_YEN,
    KEY_ABNT_C2,
    KEY_NUMPADEQUALS,
    KEY_PREVTRACK,
    KEY_AT,
    KEY_COLON,
    KEY_UNDERLINE,
    KEY_KANJI,
    KEY_STOP,
    KEY_AX,
    KEY_UNLABELED,
    KEY_NEXTTRACK,
    KEY_NUMPADENTER,
    KEY_RCONTROL,
    KEY_MUTE,
    KEY_CALCULATOR,
    KEY_PLAYPAUSE,
    KEY_MEDIASTOP,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_WEBHOME,
    KEY_NUMPADCOMMA,
    KEY_DIVIDE,
    KEY_SYSRQ,
    KEY_RMENU,
    KEY_PAUSE,
    KEY_HOME,
    KEY_UP,
    KEY_PRIOR,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_END,
    KEY_DOWN,
    KEY_NEXT,
    KEY_INSERT,
    KEY_DEL,
    KEY_LWIN,
    KEY_RWIN,
    KEY_APPS,
    KEY_POWER,
    KEY_SLEEP,
    KEY_WAKE,
    KEY_WEBSEARCH,
    KEY_WEBFAVORITES,
    KEY_WEBREFRESH,
    KEY_WEBSTOP,
    KEY_WEBFORWARD,
    KEY_WEBBACK,
    KEY_MYCOMPUTER,
    KEY_MAIL,
    KEY_MEDIASELECT,
} EKey;

typedef enum {
    MB_Left = 0,
    MB_Right,
    MB_Middle,
    MB_Wheel,
} EMouseButton;

void Input_HandleMessage( void * window, int message, int lParam, int wParam );
void Input_Flush( void );
void Input_FlushMouse( void );
void Input_SetPointerVisible( bool state );
int Input_IsKeyDown( int key );
int Input_IsKeyHit( int key );
int	Input_IsKeyUp( int key );
int Input_IsMouseDown( int button );
int Input_IsMouseHit( int button );
int Input_GetMouseX( void );
int Input_GetMouseY( void );
int Input_GetMouseWheel( void );
int Input_GetMouseXSpeed( void );
int Input_GetMouseYSpeed( void );
int Input_GetMouseWheelSpeed( void );

OLDTECH_END_HEADER

#endif